using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibraryApp
{
    public class Library
    {
        // Declaring the instance variables for the class 
        double yourOverdue;
        private string authorFullName;
        private string bookTitle;
        private int bookID;
        private string yourFullName;
        private string yourAddress;
        private string yourPhone;
        private int daysSinceCheckout;
        private char ifCheckin;


        // Default Constructor automatically generated by the compiler if no constructors have been defined for the class
        public Library()
        {
        }


        // Constructor initialize new objects
        public Library(string authorName, string title, int ID, int days, char checkin)
        {
            authorFullName = authorName;
            bookTitle = title;
            bookID = ID;
            daysSinceCheckout = days;
            SetOverDueCost();
            ifCheckin = checkin;
        }
        

        // Constructor for third object
        public Library(string authorName, string title, int ID, string yourName, string yourAddr, string yourPhone, char checkin, int days)
        {
            authorFullName = authorName;
            bookTitle = title;
            bookID = ID;
            yourFullName = yourName;
            yourAddress = yourAddr;
            daysSinceCheckout = days;
            SetOverDueCost();
            ifCheckin = checkin;
        }


        // Properties setting and returning (enable a class to expose a public way of getting and setting values, while hiding implementation or verification code)
        public string AuthorFullName
        {
            get // accessor returns the value fo the private member variable 
            {
                return authorFullName;
            }
            set // mutator assigns a new value to the private field of a type.
            {
                authorFullName = value;
            }
        }
        public string BookTitle
        {
            get
            {
                return bookTitle;
            }
            set
            {
                bookTitle = value;
            }
        }
        public int BookID
        {
            get
            {
                return bookID;
            }
            set
            {
                bookID = value;
            }
        }
        public string YourFullName
        {
            get
            {
                return yourFullName;
            }
            set
            {
                yourFullName = value;
            }
        }
        public string YourAddress
        {
            get
            {
                return yourAddress;
            }
            set
            {
                yourAddress = value;
            }
        }
        public string YourPhone
        {
            get
            {
                return yourPhone;
            }
            set
            {
                yourPhone = value;
            }
        }
        public char IfCheckin
        {
            get
            {
                return ifCheckin;
            }
            set
            {
                ifCheckin = value; 
            }
        }


        // Setting constant for the over due cost = 15.0 if days > 30
        public void SetOverDueCost()
        {
            if (daysSinceCheckout > 30) // If days since checked out is longer than 30 days, then 
                yourOverdue = 15.0;             // user will be charged a $15.00 fee 
        }


        // Return all data members using override ToString() method
        public override string ToString()
        {
            if ((ifCheckin) == 'Y' || (ifCheckin == 'y') & (daysSinceCheckout > 30)) // If user entered any day that's more than 30, the condition is accepted as true, and the info below will be the output 
                return "\n  Author Name: "
                    + authorFullName +
                    "\t Book Title: "
                    + bookTitle +
                    "\t\t\t\t Book ID: "
                    + bookID +
                    "\n\n  Your Name: "
                    + yourFullName +
                    "\t Your Address: "
                    + yourAddress +
                    "\t\t Your Phone: "
                    + yourPhone +
                    "\n\n\n Number of days your book has been checked out is " + daysSinceCheckout +
                    "\n\n Your book is overdue! You're charged a overdue fee of: " + yourOverdue.ToString("c"); // This will parse the overduecost from double into currency format 
            else if ((ifCheckin == 'N') || (ifCheckin == 'n')) // All of the info below will be displayed back to the borrower if daysSinceCheckOut is less than 30 days (When condition is false)
            {
                return "\n  Author Name: "
                + authorFullName +
                "\t Book Title: "
                + bookTitle +
                "\t\t\t\t Book ID: "
                + bookID +
                "\n\n  Your Name: "
                + yourFullName +
                "\t Your Address: "
                + yourAddress +
                "\t\t Your Phone: "
                + yourPhone +
                "\n\n\n Thank you! Your book has been successfully checked out. Remember to check your book in within the next 30 days to avoid a $15 overdue fee. Happy reading!";
            }
            else // This else statement is supposed to return all of the info back to the borrower, if he/she chose No for check-in when the program asked 
                return "\n  Author Name: "
                + authorFullName +
                "\t Book Title: "
                + bookTitle +
                "\t\t\t\t Book ID: "
                + bookID +
                "\n\n  Your Name: "
                + yourFullName +
                "\t Your Address: "
                + yourAddress +
                "\t\t Your Phone: "
                + yourPhone +
                "\n\n\n Your book has been checked in, thank you!"; 
            
        }



    }
}
